# Generated by Django 5.2.7 on 2025-11-02 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishermanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('license_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishermen.fishermanprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishermen.fishermanprofile')),
            ],
        ),
    ]
