# Generated by Django 5.2.7 on 2025-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishermen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishermanprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='fisherman_documents/'),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='license_document',
            field=models.ImageField(blank=True, null=True, upload_to='fisherman_documents/'),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='fishermanprofile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishermanprofile',
            name='license_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fishermanprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fishermanprofile',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
