# Generated by Django 5.2.7 on 2025-11-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_kg', models.FloatField()),
                ('stock', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fishcategory')),
            ],
        ),
    ]
